### ISSUE TITLE
Support chaining the extras dependencies / installing the package locally?

### ISSUE THREAD

**Issue by fohrloop** [sclabs/tox-extras#4]
It is possible to chain the extras dependencies in a pyproject.toml. Assume we are developing package called `mypkg`. It has following lines in pyproject.toml:

```toml
[project.optional-dependencies]

dev = [
    "mypkg[doc]",
    "sphinx-autobuild==2024.2.4",
    "IPython",
]

doc = [
    "sphinx==7.2.6",
    "sphinx_design==0.5.0",
    "sphinx-book-theme==1.1.2",
]
```
You can then install this locally for development with `pip install -e .[dev]` which will install the version from the current directory, and adding the `[dev]` extras. Since `mypkg[doc]` is listed there, also the `[doc]` extras will be installed. Currently (tox-extras v0.2.0), if you define in your `tox.ini`

```
[testenv:some]
description = Do something
tox_extras = dev
```

this will install the dev dependencies, here

```
    "sphinx-autobuild==2024.2.4",
    "IPython",
```

and then it will install `mypkg[doc]` *from PyPI*. Would it be possible to make it so that it installs the `mypkg` with the `[doc]` dependencies, which in this case would be

```
    "sphinx==7.2.6",
    "sphinx_design==0.5.0",
    "sphinx-book-theme==1.1.2",
```

? 

This obviously may have clash with the tox `skip_install` option, but I would assume that the `tox_extras` will install anything required in the extras, even the package itself.
